IPV4s = "ipv4s"
USER = "user"
MESSAGE_TYPE = "msg_type"
RANDOM_LOGS_FROM_USER = "random"
SSH_DURATION = "ssh_duration"
SSH_DURATION_PER_USER = "ssh_duration_per_user"
MOST_AND_LEAST_FREQUENT_USERS = "freq_users"